# Generated by Django 5.2.16 on 2026-07-21 11:39

import django.db.models.deletion
from django.db import migrations, models


def populate_visit_service_order(apps, schema_editor):
    VisitService = apps.get_model('operations', 'VisitService')
    visit_ids = VisitService.objects.values_list('visit_id', flat=True).distinct()
    for visit_id in visit_ids.iterator():
        services = VisitService.objects.filter(visit_id=visit_id).order_by('assigned_at', 'id')
        for order_number, service in enumerate(services, start=1):
            VisitService.objects.filter(pk=service.pk).update(order_number=order_number)


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('utility_type', models.CharField(blank=True, max_length=50)),
                ('branch_code', models.CharField(blank=True, max_length=30)),
                ('rated_power_kw', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('water_litres_per_minute', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('source_method', models.CharField(blank=True, max_length=50)),
                ('base_unit', models.CharField(blank=True, max_length=30)),
                ('purchase_pack_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('purchase_pack_unit', models.CharField(blank=True, max_length=30)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OperationalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=30, unique=True)),
                ('sequence', models.PositiveIntegerField(default=10)),
                ('activity_code', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(max_length=180)),
                ('role_code', models.CharField(blank=True, max_length=30)),
                ('employee_role', models.CharField(blank=True, max_length=100)),
                ('active_labour_minutes', models.PositiveIntegerField(default=0)),
                ('passive_time_minutes', models.PositiveIntegerField(default=0)),
                ('required_skill', models.CharField(blank=True, max_length=100)),
                ('allowed_staff_type', models.CharField(blank=True, max_length=120)),
                ('default_customer_type', models.CharField(blank=True, max_length=30)),
                ('is_skippable', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('standard_output_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('output_unit', models.CharField(blank=True, max_length=30)),
                ('procedure_notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterModelOptions(
            name='visitservice',
            options={'ordering': ['visit_id', 'order_number', 'id']},
        ),
        migrations.AddField(
            model_name='service',
            name='current_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='customer_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='service',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='visitservice',
            name='order_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(populate_visit_service_order, migrations.RunPython.noop),
        migrations.AddField(
            model_name='visittask',
            name='active_labour_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visittask',
            name='passive_time_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visittask',
            name='sub_service_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='visittask',
            name='title',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterUniqueTogether(
            name='visitservice',
            unique_together={('visit', 'order_number')},
        ),
        migrations.AddField(
            model_name='visittask',
            name='source_operational_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.operationaltask'),
        ),
        migrations.AddField(
            model_name='operationaltask',
            name='sub_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='operations.subservice'),
        ),
        migrations.CreateModel(
            name='TaskEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=30, unique=True)),
                ('quantity_required', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('equipment_usage_minutes', models.PositiveIntegerField(default=0)),
                ('utility_type', models.CharField(blank=True, max_length=50)),
                ('utility_minutes', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.equipment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_requirements', to='operations.operationaltask')),
            ],
            options={
                'ordering': ['equipment__name'],
            },
        ),
        migrations.CreateModel(
            name='TaskInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=30, unique=True)),
                ('standard_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('waste_percent', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('effective_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('mapping_status', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.inventoryitem')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_inventory', to='operations.service')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_requirements', to='operations.operationaltask')),
            ],
            options={
                'ordering': ['inventory__name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=30, unique=True)),
                ('sequence', models.PositiveIntegerField(default=10)),
                ('required_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('mandatory', models.BooleanField(default=True)),
                ('mapping_status', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_details', to='operations.service')),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_details', to='operations.subservice')),
            ],
            options={
                'ordering': ['sequence', 'id'],
                'unique_together': {('service', 'sub_service', 'sequence')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='operationaltask',
            unique_together={('sub_service', 'sequence')},
        ),
    ]
