# Generated by Django 5.2.17 on 2026-09-06 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_visit_service_reassignment_and_invoice_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationaltask',
            name='staff_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='operationaltask',
            name='supports_waiting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visittask',
            name='staff_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visittask',
            name='supports_waiting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visittask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('WAITING', 'Processing / setting'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='TaskTimingSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ACTIVE', 'Hands-on'), ('WAITING', 'Waiting')], max_length=10)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timing_segments', to='operations.visittask')),
            ],
            options={
                'ordering': ['started_at', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('task',), name='one_open_task_timing_segment')],
            },
        ),
    ]
