# Generated by Django 5.2.17 on 2026-10-02 11:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_alter_profile_role_branchduty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOPWorkbookImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('filename', models.CharField(max_length=160)),
                ('sha256', models.CharField(max_length=64)),
                ('workbook', models.BinaryField(default=bytes)),
                ('master_digest', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=2000)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting confirmation'), ('APPLIED', 'Imported'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('master_snapshot', models.BinaryField(default=bytes)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sop_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
