# Generated by Django 5.2.17 on 2026-10-03 10:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_staffcsvimport_profile_experience_profile_salary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchCSVImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('filename', models.CharField(max_length=160)),
                ('sha256', models.CharField(max_length=64)),
                ('master_digest', models.CharField(max_length=64)),
                ('plan', models.JSONField(default=dict, editable=False)),
                ('summary', models.JSONField(default=dict, editable=False)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting confirmation'), ('APPLIED', 'Imported'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_csv_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
